### ISSUE TITLE
Support proof verification

### ISSUE THREAD

**Issue by tahpot** [verida/proof-connector-dapp#4]
It will be helpful to have an easy way to request and verify a proof.

- [x] Create a `/verify` endpoint
- [x] Create a `Login` button that opens the Verida SSO modal allowing the user to sign in. [See SSO documentation](https://developers.verida.network/docs/tutorial/SSO)
- [x] Once logged in, show a `Request credential` button that generates an inbox request for the user to share a credential (similar to missions)
- [x] Once the credential is received, verify the proof contained within the credential. Verify the proof using either the zkpass and reclaim protocol SDK, depending on the type of proof
- [x] Display a message saying if the proof was successfully verified or not

**Comment by icetrust0212** [comment]
https://github.com/verida/proof-connector-dapp/pull/10
